name: Basic Code Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Check Python syntax
      run: |
        # Simple syntax check on Python files
        find . -name "*.py" -type f -exec python -m py_compile {} \;
    - name: Verify project structure
      run: |
        # Check that critical directories exist
        echo "Verifying project structure..."
        if [ -d "src" ]; then
          echo "✓ src directory found"
        else
          echo "⚠️ src directory not found"
        fi
        if [ -f "requirements.txt" ]; then
          echo "✓ requirements.txt found"
        else
          echo "⚠️ requirements.txt not found"
        fi
    - name: Success
      run: |
        echo "✅ Basic validation completed successfully" 